### ISSUE TITLE
Cross Chain Bridge

### ISSUE THREAD

**Issue by MaxEKB03** [MaxEKB03/BLOCKCHAIN#2]
Need to develop a light cross chain bridge between two geth test networks

**Comment by MaxEKB03** [comment]
In my mind, tokens that going to changing to another tokens on another blockchain need burn. And new tokens on second blockchain need to mint

`Tokens cycle on blockchain`

**Comment by MaxEKB03** [comment]
- Geth test network is created by docker's containers
- Smart-contracts has administrating by owner (admins)

**Comment by MaxEKB03** [comment]
> In my mind, tokens that going to changing to another tokens on another blockchain need burn. And new tokens on second blockchain need to mint
> 
> `Tokens cycle on blockchain`

Or

add a liquidity pool  to storage a tokens like wBTC or another (new tokens we can't mint, but, if its our tokens, we can!)

**Comment by elton** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!the-real-astro, @Osub, @warengonzaga, @Diamondzminde, @unbanksytv, @nawiq7208, @tommyliu9, @kumaryash90, @thestriver, @poteitoo, @antho31, @bliuk, @anuraglol, @jneygor8504, @yaojunluo, @justinbalaguer, @michhub-dev, @lekandev, @iiiyu, @Opabby
